# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyladies_harare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
