# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0003_remove_proposal_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('details', markitup.fields.MarkupField(help_text='Describe what the talk you are suggesting is about', no_rendered_field=True)),
                ('_details_rendered', models.TextField(blank=True, editable=False)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
                ('talk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.Talk_Type')),
            ],
        ),
    ]
